export { default as Loader } from './Loader'
export { default as Footer } from './Footer'
export { default as Navbar } from './Navbar'
export { default as Services } from './Services'
export { default as Transactions } from './Transactions'
export { default as Welcome } from './Welcome'